### ISSUE TITLE
Images too large for smaller screens.

### ISSUE THREAD

**Issue by AeroActuallyDev** [GuildedAPI/docs#6]
The images are way too large for smaller screens, eg laptop (1366x768)

![image](https://user-images.githubusercontent.com/83130968/116808658-f5c4e180-ab31-11eb-8c3c-e07f6a659b9f.png)

**Comment by AeroActuallyDev** [comment]
Better image
![image](https://user-images.githubusercontent.com/83130968/116808703-40465e00-ab32-11eb-9967-9f160778fa6d.png)

**Comment by shayypy** [comment]
It's really just meant as a repository of assets, not a gallery for viewing. If you want to make them display smaller, you should submit a PR.
